SELECT PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,CANTIDAD_USO
FROM  PERSONA, AFILIADO, BENEFICIO_AFILIADO
WHERE PERSONA.COD_PERSONA = AFILIADO.COD_PERSONA  AND AFILIADO.COD_AFILIADO = BENEFICIO_AFILIADO.COD_AFILIADO;
